package com.mycompany.ej18v2;


public class interfaz2 extends javax.swing.JFrame {
    

    

    /**
     * Creates new form interfaz
     */
    public interfaz2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        LadoTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PerimetroTF = new javax.swing.JTextField();
        AlturaTF = new javax.swing.JTextField();
        AreaTF = new javax.swing.JTextField();
        CirculoBT = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ladoCuadradoTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        AreaCuadradoTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        PerimetroCuadradoTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        baseRTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        AreaRectanguloTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        PerimetroRectanguloTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        alturaRTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        areatrTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        perimetrotrTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        hipotenusaTF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        basetrTF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        alturatrTF = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tipoTrianguloTF = new javax.swing.JTextField();
        cuadradoBT = new javax.swing.JButton();
        rectanguloBT = new javax.swing.JButton();
        trBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Ingrese el lado: ");

        LadoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LadoTFActionPerformed(evt);
            }
        });

        jLabel1.setText("Perimetro: ");

        jLabel2.setText("Altura: ");

        jLabel3.setText("Area: ");

        PerimetroTF.setEditable(false);
        PerimetroTF.setToolTipText("");
        PerimetroTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerimetroTFActionPerformed(evt);
            }
        });

        AlturaTF.setEditable(false);
        AlturaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlturaTFActionPerformed(evt);
            }
        });

        AreaTF.setEditable(false);
        AreaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaTFActionPerformed(evt);
            }
        });

        CirculoBT.setText("Resolver Circulo");
        CirculoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CirculoBTActionPerformed(evt);
            }
        });

        jLabel5.setText("CIRCULO");

        jLabel6.setText("RECTANGULO");

        jLabel7.setText("CUADRADO");

        jLabel8.setText("TRIANGULO RECTANGULO");

        jLabel9.setText("Ingrese el lado: ");

        ladoCuadradoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ladoCuadradoTFActionPerformed(evt);
            }
        });

        jLabel10.setText("Area: ");

        AreaCuadradoTF.setEditable(false);
        AreaCuadradoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaCuadradoTFActionPerformed(evt);
            }
        });

        jLabel11.setText("Perimetro: ");

        PerimetroCuadradoTF.setEditable(false);
        PerimetroCuadradoTF.setToolTipText("");
        PerimetroCuadradoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerimetroCuadradoTFActionPerformed(evt);
            }
        });

        jLabel12.setText("Ingrese la base:");

        baseRTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseRTFActionPerformed(evt);
            }
        });

        jLabel13.setText("Area: ");

        AreaRectanguloTF.setEditable(false);
        AreaRectanguloTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaRectanguloTFActionPerformed(evt);
            }
        });

        jLabel14.setText("Perimetro: ");

        PerimetroRectanguloTF.setEditable(false);
        PerimetroRectanguloTF.setToolTipText("");
        PerimetroRectanguloTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerimetroRectanguloTFActionPerformed(evt);
            }
        });

        jLabel15.setText("Ingrese la altura:");

        alturaRTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaRTFActionPerformed(evt);
            }
        });

        jLabel16.setText("Area: ");

        areatrTF.setEditable(false);
        areatrTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areatrTFActionPerformed(evt);
            }
        });

        jLabel17.setText("Perimetro: ");

        perimetrotrTF.setEditable(false);
        perimetrotrTF.setToolTipText("");
        perimetrotrTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perimetrotrTFActionPerformed(evt);
            }
        });

        jLabel18.setText("Hipotenusa:");

        hipotenusaTF.setEditable(false);
        hipotenusaTF.setToolTipText("");
        hipotenusaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hipotenusaTFActionPerformed(evt);
            }
        });

        jLabel19.setText("Ingrese la base:");

        basetrTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basetrTFActionPerformed(evt);
            }
        });

        jLabel20.setText("Ingrese la altura:");

        alturatrTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturatrTFActionPerformed(evt);
            }
        });

        jLabel21.setText("Tipo de Triangulo:");

        tipoTrianguloTF.setEditable(false);
        tipoTrianguloTF.setToolTipText("");
        tipoTrianguloTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoTrianguloTFActionPerformed(evt);
            }
        });

        cuadradoBT.setText("Resolver Cuadrado");
        cuadradoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadradoBTActionPerformed(evt);
            }
        });

        rectanguloBT.setText("Resolver Rectangulo");
        rectanguloBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectanguloBTActionPerformed(evt);
            }
        });

        trBT.setText("Resolver Triangulo Rectangulo");
        trBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LadoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PerimetroTF)
                                    .addComponent(AlturaTF)
                                    .addComponent(AreaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ladoCuadradoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(AreaCuadradoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PerimetroCuadradoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(cuadradoBT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(alturaRTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(baseRTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tipoTrianguloTF, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(areatrTF)
                                                .addComponent(perimetrotrTF, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(hipotenusaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(alturatrTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(basetrTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rectanguloBT)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(AreaRectanguloTF)
                                            .addComponent(PerimetroRectanguloTF, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140))))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(CirculoBT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(283, 283, 283))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(trBT)
                        .addGap(124, 124, 124))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(LadoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(PerimetroTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(AlturaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AreaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(baseRTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(alturaRTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(AreaRectanguloTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(PerimetroRectanguloTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CirculoBT)
                    .addComponent(rectanguloBT))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ladoCuadradoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(AreaCuadradoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(PerimetroCuadradoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(cuadradoBT))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(basetrTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(alturatrTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(areatrTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(perimetrotrTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(hipotenusaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tipoTrianguloTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(trBT)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LadoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LadoTFActionPerformed
        
       
        
        
    }//GEN-LAST:event_LadoTFActionPerformed

    private void PerimetroTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerimetroTFActionPerformed
        
        
                            
       
       
        
    }//GEN-LAST:event_PerimetroTFActionPerformed

    private void CirculoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CirculoBTActionPerformed
        
        double ladocirculo = Double.parseDouble( LadoTF.getText());        
        Triangulo t1 = new Triangulo(ladocirculo);        
        PerimetroTF.setText(String.valueOf(t1.perimetro()));
        AlturaTF.setText(String.valueOf(t1.altura()));
        AreaTF.setText(String.valueOf(t1.area(t1.altura())));
        
        
            
            
            
            
            
            
            
        

    }//GEN-LAST:event_CirculoBTActionPerformed

    private void AlturaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlturaTFActionPerformed
        
    }//GEN-LAST:event_AlturaTFActionPerformed

    private void AreaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaTFActionPerformed
        
    }//GEN-LAST:event_AreaTFActionPerformed

    private void ladoCuadradoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ladoCuadradoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ladoCuadradoTFActionPerformed

    private void AreaCuadradoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaCuadradoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaCuadradoTFActionPerformed

    private void PerimetroCuadradoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerimetroCuadradoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerimetroCuadradoTFActionPerformed

    private void baseRTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseRTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baseRTFActionPerformed

    private void AreaRectanguloTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaRectanguloTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaRectanguloTFActionPerformed

    private void PerimetroRectanguloTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerimetroRectanguloTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerimetroRectanguloTFActionPerformed

    private void alturaRTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaRTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaRTFActionPerformed

    private void areatrTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areatrTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areatrTFActionPerformed

    private void perimetrotrTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perimetrotrTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perimetrotrTFActionPerformed

    private void hipotenusaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hipotenusaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hipotenusaTFActionPerformed

    private void basetrTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basetrTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basetrTFActionPerformed

    private void alturatrTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturatrTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturatrTFActionPerformed

    private void tipoTrianguloTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoTrianguloTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoTrianguloTFActionPerformed

    private void cuadradoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadradoBTActionPerformed
        int lado_cuadrado = Integer.parseInt( String.valueOf(ladoCuadradoTF.getText()));
            Cuadrado cu = new Cuadrado(lado_cuadrado);
            AreaCuadradoTF.setText(String.valueOf(cu.calcularArea()));
            PerimetroCuadradoTF.setText(String.valueOf(cu.calcularPerímetro()));
    }//GEN-LAST:event_cuadradoBTActionPerformed

    private void rectanguloBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectanguloBTActionPerformed
        int baseR = Integer.parseInt( String.valueOf(baseRTF.getText()));
            int alturaR = Integer.parseInt( String.valueOf(alturaRTF.getText()));
            
            Rectángulo r1 = new Rectángulo(baseR, alturaR);
            AreaRectanguloTF.setText(String.valueOf(r1.calcularArea()));
            PerimetroRectanguloTF.setText(String.valueOf(r1.calcularPerímetro()));
    }//GEN-LAST:event_rectanguloBTActionPerformed

    private void trBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trBTActionPerformed
        int baseTR = Integer.parseInt( String.valueOf(basetrTF.getText()));
            int alturaTR = Integer.parseInt( String.valueOf(alturatrTF.getText()));
            
            TriánguloRectángulo tr1 = new TriánguloRectángulo(baseTR, alturaTR);
            areatrTF.setText(String.valueOf(tr1.calcularArea()));
            perimetrotrTF.setText(String.valueOf(tr1.calcularPerímetro()));
            hipotenusaTF.setText(String.valueOf(tr1.calcularHipotenusa()));
            tipoTrianguloTF.setText(String.valueOf(tr1.determinarTipoTriángulo()));
    }//GEN-LAST:event_trBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlturaTF;
    private javax.swing.JTextField AreaCuadradoTF;
    private javax.swing.JTextField AreaRectanguloTF;
    private javax.swing.JTextField AreaTF;
    private javax.swing.JButton CirculoBT;
    private javax.swing.JTextField LadoTF;
    private javax.swing.JTextField PerimetroCuadradoTF;
    private javax.swing.JTextField PerimetroRectanguloTF;
    private javax.swing.JTextField PerimetroTF;
    private javax.swing.JTextField alturaRTF;
    private javax.swing.JTextField alturatrTF;
    private javax.swing.JTextField areatrTF;
    private javax.swing.JTextField baseRTF;
    private javax.swing.JTextField basetrTF;
    private javax.swing.JButton cuadradoBT;
    private javax.swing.JTextField hipotenusaTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField ladoCuadradoTF;
    private javax.swing.JTextField perimetrotrTF;
    private javax.swing.JButton rectanguloBT;
    private javax.swing.JTextField tipoTrianguloTF;
    private javax.swing.JButton trBT;
    // End of variables declaration//GEN-END:variables
}
